--- 
title: "Handout_V2"
author: "Pierre Bauche"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
link-citations: yes
---


# **Information**

## Usefull ressource
Feature engenering : http://www.feat.engineering/review-predictive-modeling-process.html
Semi supervized learning : https://www.analyticsvidhya.com/blog/2017/09/pseudo-labelling-semi-supervised-learning-technique/  
    - Machine Learning wth unlabbeled data : psuedo labeling
  

## todo
  - create Blogdown
  - tydiverse package
  - Tensorflow for deep learning : open source software library developed at google for complex computation
  
## interesting stuff
  - polynomial regression using kernel smoothing
  - Logistic regression using 5 fold stratified cross validation
  - blockchain data science
  - reinforcement learning
  - adversarial training 
  -Deep Learning
    - microsoft service
    - Tensorflow  : read exemple
    - RKWard : free and open source Graphical User Interface for the R software
  - ML with H2O, lime, Keras
  - spark R
  - image recognizing with R
  - sentiment analysis = microsoft azure
  

- data privacy
- data quality control

- Web developpement
  - Shiny : (microsoft azure serveur pour upload
  - Rmarckodw : 
  - blogdown (Hugo)


- Insurance
  - fraud
  - underwriting models : predict somebody’s insurance risk
  - marketing predition
  - customer segmentation
